<?php

return [
    'title' => 'Decision Templates',
    'description' => 'Reusable templates for producing final decision documents for the applicant and respondent.',
    'new' => 'New Decision Template',
    'create' => 'Create decision template',
    'create_help' => 'Define a reusable layout. Use placeholders like {{applicant_name}} that are filled in when generating a decision\'s final output.',
    'edit' => 'Edit decision template',
    'edit_help' => 'Update the layout and placeholders for this decision template.',

    'actions' => [
        'new_template' => 'New template',
        'cancel' => 'Cancel',
        'save_template' => 'Save template',
        'edit' => 'Edit',
        'delete' => 'Delete',
        'delete_template' => 'Delete this decision template?',
    ],

    'table' => [
        'title' => 'Title',
        'category' => 'Category',
        'placeholders' => 'Placeholders',
        'updated' => 'Updated',
        'actions' => 'Actions',
        'empty' => 'No decision templates yet.',
        'none' => 'None',
        'missing' => '—',
    ],

    'form' => [
        'title' => 'Title',
        'category' => 'Category',
        'category_placeholder' => 'e.g. Final judgment, Ruling',
        'is_default' => 'Use as the default layout',
        'is_default_help' => 'The default template is used when a decision is generated without choosing a template. Only one can be default.',
        'placeholders' => 'Placeholders',
        'placeholders_placeholder' => 'applicant_name, respondent_name, case_number',
        'placeholders_example' => 'Comma or newline separated. Each becomes a {{token}} you can use in the body.',
        'placeholders_help' => 'Available: <code>{{applicant_name}}</code>, <code>{{respondent_name}}</code>, <code>{{case_number}}</code>, <code>{{case_file_number}}</code>, <code>{{judge_name}}</code>, <code>{{decision_date}}</code>, <code>{{decision_content}}</code>, <code>{{decision_name}}</code>, <code>{{judge_one}}</code>, <code>{{judge_two}}</code>, <code>{{judge_three}}</code>, <code>{{judge_one_vote}}</code>, <code>{{judge_two_vote}}</code>, <code>{{judge_three_vote}}</code>, <code>{{judges_signatures}}</code>',
        'header_image' => 'Header image',
        'footer_image' => 'Footer image',
        'header_current' => 'Current header: :file',
        'footer_current' => 'Current footer: :file',
        'remove_header' => 'Remove header image',
        'remove_footer' => 'Remove footer image',
        'body' => 'Body',
        'body_placeholder' => 'Write the decision layout here. Insert tokens such as {{applicant_name}} and {{decision_content}}.',
        'body_help' => 'You can use the placeholder tokens above; they are replaced when the final output is generated.',
    ],

    'output' => [
        'heading' => 'Final output',
        'choose_template' => 'Generate the final decision PDF. Choose a template, or use the default layout.',
        'select' => 'Select template',
        'default_layout' => 'Default layout',
        'generate' => 'Generate final output',
        'download' => 'Download',
        'none_available' => 'No decision templates available. Create one first.',
    ],

    // Clean, single-language labels used only on the rendered PDF.
    'pdf' => [
        'date' => 'Date',
        'case_number' => 'Case No.',
        'applicant' => 'Applicant',
        'respondent' => 'Respondent',
        'judge' => 'Judge :number',
        'judges' => 'Judges',
        'header_title' => 'Federal Democratic Republic of Ethiopia',
        'header_subtitle' => 'Tribunal — Final Decision',
        'footer_note' => 'This document is generated by the court management system.',
    ],
];
